# Generated by Django 4.0.1 on 2022-03-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_alter_share_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='share',
            options={'ordering': ['-transaction__reference__date_trans']},
        ),
    ]
