# Generated by Django 4.0.1 on 2022-03-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_date_joined'),
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='members.member'),
        ),
    ]
