# Generated by Django 4.0.1 on 2022-03-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_alter_saving_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saving',
            options={'ordering': ['-transaction__reference__date_trans']},
        ),
    ]
