# Generated by Django 4.0.1 on 2022-03-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-transaction__reference__date_trans'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
    ]
