# Generated by Django 4.0.1 on 2022-04-27 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_banktransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.banktransaction'),
        ),
    ]
