# Generated by Django 4.0.1 on 2022-04-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='status',
            field=models.CharField(choices=[('imported', 'Imported'), ('assigned', 'Assigned'), ('partial_assigned', 'Partial Assigned'), ('cancelled', 'Canceled')], max_length=20),
        ),
    ]
