# Generated by Django 4.0.1 on 2022-06-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_bankstatement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankStatement',
        ),
    ]
