# Generated by Django 4.0.1 on 2022-06-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_bankstatement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banktransaction',
            name='filename',
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='bankstatement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.bankstatement'),
        ),
    ]
