# Generated by Django 4.0.1 on 2022-02-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-first_name', 'middle_name', 'last_name']},
        ),
    ]
