# Generated by Django 4.0.1 on 2022-03-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loan_member'),
        ('authentication', '0002_alter_member_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
