# Generated by Django 4.0.1 on 2022-05-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change',
            field=models.BooleanField(default=False),
        ),
    ]
