# Generated by Django 4.0.1 on 2022-05-17 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_password_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_change',
        ),
    ]
