# Generated by Django 4.0.1 on 2022-05-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change',
            field=models.BooleanField(default=False),
        ),
    ]
