# Generated by Django 4.0.1 on 2022-02-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loanlimits_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanformfee',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('emergence', 'Emergence')], default='normal', max_length=20),
        ),
    ]
