# Generated by Django 4.0.1 on 2022-02-24 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loanformfee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrepayment',
            name='amount',
        ),
        migrations.AddField(
            model_name='loan',
            name='repayment_status',
            field=models.CharField(choices=[('issued', 'Normal'), ('repayment', 'Repayment'), ('completed', 'Completed'), ('default', 'Default')], default='issued', max_length=20),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='loan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='loans.loan'),
        ),
    ]
