# Generated by Django 4.0.1 on 2022-03-30 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_banktransaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0006_alter_loan_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-transaction__reference__date_trans'], 'verbose_name': 'Loan'},
        ),
        migrations.AlterModelOptions(
            name='loanrepayment',
            options={'ordering': ['-transaction__reference__date_trans'], 'verbose_name': 'Loan Repayment', 'verbose_name_plural': 'Loan Repayments'},
        ),
        migrations.AlterField(
            model_name='loan',
            name='repayment_status',
            field=models.CharField(choices=[('issued', 'Issued'), ('repayment', 'Repayment'), ('completed', 'Completed'), ('default', 'Default')], default='issued', max_length=20),
        ),
        migrations.CreateModel(
            name='RepaymentsPrinciple',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.FloatField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepaymentsInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.FloatField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
