# Generated by Django 4.0.1 on 2022-04-21 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_loan_options_alter_loanrepayment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repaymentsinterest',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='repaymentsinterest',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='repaymentsprinciple',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='repaymentsprinciple',
            name='transaction',
        ),
        migrations.AddField(
            model_name='repaymentsinterest',
            name='loan_repayement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.loanrepayment'),
        ),
        migrations.AddField(
            model_name='repaymentsprinciple',
            name='loan_repayement',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.loanrepayment'),
        ),
    ]
