# Generated by Django 4.0.1 on 2022-04-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_remove_repaymentsinterest_loan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repaymentsinterest',
            old_name='loan_repayement',
            new_name='loan_repayment',
        ),
        migrations.RenameField(
            model_name='repaymentsprinciple',
            old_name='loan_repayement',
            new_name='loan_repayment',
        ),
    ]
