# Generated by Django 4.0.1 on 2022-04-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_rename_loan_repayement_repaymentsinterest_loan_repayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repaymentsprinciple',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='repaymentsprinciple',
            name='loan_repayment',
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='interest_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='principle_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RepaymentsInterest',
        ),
        migrations.DeleteModel(
            name='RepaymentsPrinciple',
        ),
    ]
