# Generated by Django 4.0.1 on 2022-03-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
