# Generated by Django 4.0.1 on 2022-05-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password_change',
            field=models.BooleanField(default=False),
        ),
    ]
