# Generated by Django 4.0.1 on 2022-05-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_password_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='password_change',
        ),
    ]
